<?php

namespace App\Http\Controllers\Api\V1\Freepik;

use App\Http\Controllers\Controller;
use App\Services\Freepik\FreepikDownloadService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use RuntimeException;
use Throwable;

class RemoveBackgroundController extends Controller
{
    public function __construct(
        protected FreepikDownloadService $freepikDownloadService
    ) {
    }

    public function __invoke(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'image_url' => [
                'required',
                'url',
                'max:2048',
            ],
        ]);

        try {
            $result = $this->freepikDownloadService->removeBackground(
                $validated['image_url']
            );

            $data = $this->normalizeResponseData($result);

            return response()->json([
                'success' => true,
                'message' => 'Background removed successfully.',
                'data' => $data,
            ]);
        } catch (Throwable $exception) {
            $status = (int) $exception->getCode();

            if ($status < 400 || $status > 599) {
                $status = 500;
            }

            return response()->json([
                'success' => false,
                'message' => $exception->getMessage(),
            ], $status);
        }
    }

    /**
     * Normalize the service response and replace the direct public/storage URL
     * with the named Laravel API route. This makes Fabric.js load the generated
     * image through Laravel's CORS middleware instead of the static-file server.
     *
     * @param mixed $result
     * @return array<string, mixed>
     */
    private function normalizeResponseData(mixed $result): array
    {
        if (is_string($result)) {
            $data = ['url' => $result];
        } elseif (is_array($result)) {
            $data = $result;
        } elseif (is_object($result)) {
            $data = (array) $result;
        } else {
            throw new RuntimeException(
                'The background-removal service returned an invalid response.'
            );
        }

        $sourceUrl = $this->firstAvailableUrl($data);

        if ($sourceUrl === null) {
            throw new RuntimeException(
                'The background-removal service did not return an image URL.'
            );
        }

        $corsSafeUrl = $this->toCorsSafeUrl($sourceUrl);

        // Preserve the source image URL separately so the frontend can offer
        // a "Restore background" action after replacing the canvas image.
        $originalUrl = isset($data['original'])
            && is_string($data['original'])
            && trim($data['original']) !== ''
                ? trim($data['original'])
                : null;

        // Keep every response key expected by the frontend. All keys point to
        // the same final transparent image generated by the service.
        $normalized = array_merge($data, [
            'url' => $corsSafeUrl,
            'file_url' => $corsSafeUrl,
            'processed_url' => $corsSafeUrl,
            'high_resolution' => $corsSafeUrl,
            'preview' => $corsSafeUrl,
        ]);

        if ($originalUrl !== null) {
            $normalized['original'] = $originalUrl;
        }

        return $normalized;
    }

    /**
     * @param array<string, mixed> $data
     */
    private function firstAvailableUrl(array $data): ?string
    {
        foreach (['url', 'high_resolution', 'preview', 'original'] as $key) {
            $value = $data[$key] ?? null;

            if (is_string($value) && trim($value) !== '') {
                return trim($value);
            }
        }

        return null;
    }

    /**
     * Convert only generated local removed-background paths. If the service
     * deliberately returns another URL type, preserve it unchanged.
     */
    private function toCorsSafeUrl(string $sourceUrl): string
    {
        $path = parse_url($sourceUrl, PHP_URL_PATH);

        if (!is_string($path) || $path === '') {
            $path = $sourceUrl;
        }

        $normalizedPath = str_replace('\\', '/', rawurldecode($path));

        if (!preg_match(
            '#(?:^|/)designer/removed-backgrounds/([^/]+)$#i',
            $normalizedPath,
            $matches
        )) {
            return $sourceUrl;
        }

        $filename = $matches[1] ?? '';

        if (
            $filename === '' ||
            $filename !== basename($filename) ||
            !preg_match('/^[A-Za-z0-9._-]+$/', $filename)
        ) {
            throw new RuntimeException(
                'The background-removal service returned an invalid filename.'
            );
        }

        $extension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));

        if (!in_array($extension, ['png', 'jpg', 'jpeg', 'webp'], true)) {
            throw new RuntimeException(
                'The generated background image has an unsupported format.'
            );
        }

        return route('designer.removed-backgrounds.show', [
            'filename' => $filename,
        ]);
    }
}
